# Generated by Django 4.1.7 on 2025-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0002_entity_country_entity_gst_entity_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohocustomer',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zohocustomer',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zohocustomer',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
