import os
import pdfkit
from enum import Enum
import logging
ROLE_PERMISSIONS = {
    "pmo": [
        {
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "updates": True,
            "my_projects": True,
            "active_inactive": True,
            "close": True,
            "functionality": "project",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "add_to_project": True,
            "mail": True,
            "share_profile": True,
            "summary_report": True,
            "updates": True,
            "functionality": "coach",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "accept": True,
            "reject": True,
            "functionality": "standard_field",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "approve": True,
            "reject": True,
            "add_updates": True,
            "functionality": "registered_coach",
        },
        {
            "copy_link": True,
            "edit": True,
            "view": True,
            "send_mail": True,
            "functionality": "share_profile",
        },
        {
            "view": True,
            "functionality": "find_coach",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "functionality": "facilitator",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "approve": True,
            "reject": True,
            "add_updates": True,
            "functionality": "registered_facilitator",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "insights": True,
            "view_inside": True,
            "reject": True,
            "add_updates": True,
            "my_assessments": True,
            "functionality": "assessment",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "questionnaire",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "competency",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "questions",
        },
        {
            "functionality": "form_templates",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
        },
        {
            "download": True,
            "view": True,
            "my_coaching_session_reports": True,
            "functionality": "coaching_session_reports",
        },
        {
            "download": True,
            "view": True,
            "my_live_session_reports": True,
            "functionality": "live_session_reports",
        },
        {
            "download": True,
            "view": True,
            "my_assessment_reports": True,
            "functionality": "assessments_reports",
        },
        {
            "download": True,
            "view": True,
            "my_course_reports": True,
            "functionality": "course_reports",
        },
        {
            "download": True,
            "view": True,
            "my_feedback_reports": True,
            "view_project_feedbacks": True,
            "functionality": "feedback_reports",
        },
        {
            "download": True,
            "view": True,
            "my_quiz_reports": True,
            "functionality": "quiz_reports",
        },
        {
            "download": True,
            "view": True,
            "my_competency_reports": True,
            "functionality": "competency_reports",
        },
        {
            "download": True,
            "view": True,
            "functionality": "coach_ratings",
        },
        {
            "download": True,
            "view": True,
            "my_participant_reports": True,
            "functionality": "participant_reports",
        },
        {
            "generate": True,
            "download": True,
            "view": True,
            "my_closure_reports": True,
            "functionality": "closure_reports",
        },
        {
            "generate": True,
            "download": True,
            "view": True,
            "my_cancelled_session_reports": True,
            "functionality": "cancelled_session_reports",
        },
        {
            "upload": True,
            "edit": True,
            "view": True,
            "create": True,
            "view_engagements": True,
            "functionality": "coachee",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "view_line_items": True,
            "download": True,
            "download_invoice": True,
            "preview_invoice": True,
            "updates": True,
            "my_purchase_orders": True,
            "functionality": "purchase_order",
        },
        {
            "functionality": "sales_order",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_sales_order": True,
        },
        {
            "functionality": "coach_finances",
            "view": True,
            "download": True,
        },
        {
            "functionality": "project_gm",
            "view": True,
            "download": True,
        },
        {
            "functionality": "facilitator_finances",
            "view": True,
            "po_analytics": True,
            "expenses": True,
            "download": True,
        },
        {
            "functionality": "project_finances",
            "view": True,
            "download": True,
        },
        {
            "functionality": "leaderboard",
            "view": True,
            "download": True,
        },
        {
            "functionality": "course_templates",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
        },
        {
            "functionality": "certificate",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
        },
        {
            "functionality": "video_library",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "play": True,
        },
        {
            "functionality": "pdf_library",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
        },
        {
            "functionality": "files_library",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "download": True,
        },
        {
            "functionality": "assignments",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
        },
        {
            "functionality": "resources",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "update_status": True,
            "assign_to_coachee": True,
            "create_tag": True,
            "approval": True,
            "preview": True,
        },
        {
            "functionality": "request_avalibility",
            "view": True,
            "download_avaliable_slots": True,
            "create": True,
            "edit": True,
            "delete": True,
        },
        {
            "functionality": "all_slots",
            "view": True,
            "edit": True,
        },
        {
            "functionality": "organization_and_hr",
            "view": True,
            "add_hr": True,
            "add_organization": True,
            "edit_hr": True,
            "edit_organization": True,
        },
        {
            "functionality": "email_templates",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "send_email": True,
            "preview": True,
        },
        {
            "functionality": "contract",
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
            "view": True,
            "master_coach_contract": True,
            "facilitator_contract": True,
            "download_coach_contract": True,
            "download_facilitator_contract": True,
        },
        {
            "functionality": "mira_ai",
            "mira_ai": True,
            "mira_ai_history": True,
            "chatbot_history": True,
        },
        {
            "functionality": "user_and_roles",
            "view": True,
        },
        {
            "functionality": "permissions",
            "view": True,
            "edit": True,
        },
        {
            "functionality": "meetings",
            "view": True,
        },
        {
            "functionality": "actions",
            "action_list": True,
            "analysis": True,
            "ai_analysis": True,
        },
        {
            "functionality": "finance_sheet",
            "view": True,
            "download": True,
        },
        {
            "functionality": "participants",
            "view": True,
            "download": True,
        },
        {
            "functionality": "performace_evaluation",
            "view": True,
            "download": True,
        },
    ],
    "curriculum": [
        {
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "updates": True,
            "my_projects": True,
            "functionality": "project",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "summary_report": True,
            "updates": True,
            "functionality": "coach",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "accept": True,
            "reject": True,
            "functionality": "standard_field",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "functionality": "facilitator",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "download": True,
            "approve": True,
            "reject": True,
            "add_updates": True,
            "functionality": "registered_facilitator",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "insights": True,
            "view_inside": True,
            "reject": True,
            "add_updates": True,
            "my_assessments": True,
            "functionality": "assessment",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "questionnaire",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "competency",
        },
        {
            "create": True,
            "edit": True,
            "delete": True,
            "view": True,
            "functionality": "questions",
        },
        {
            "functionality": "course_templates",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
        },
        {
            "functionality": "resources",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "update_status": True,
            "assign_to_coachee": True,
            "create_tag": True,
            "approval": True,
            "preview": True,
        },
        {
            "functionality": "contract",
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
            "view": True,
            "master_coach_contract": True,
            "facilitator_contract": True,
            "download_coach_contract": True,
            "download_facilitator_contract": True,
        },
        {
            "functionality": "mira_ai",
            "mira_ai": True,
            "mira_ai_history": True,
            "chatbot_history": True,
        },
        {
            "functionality": "permissions",
            "view": True,
            "edit": True,
        },
        {
            "functionality": "ai",
            "ai_guruji": True,
        },
        {
            "functionality": "form_templates",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
        },
        {
            "functionality": "form",
            "view": True,
            "create": True,
            "edit": True,
            "delete": True,
            "preview": True,
            "whatsapp_notification": True,
            "email_notification": True,
        },
        {
            "download": True,
            "view": True,
            "view_project_feedbacks": True,
            "functionality": "feedback",
        },
        {
            "functionality": "pre_study",
            "create": True,
            "delete": True,
            "edit": True,
            "view": True,
            "view_deatils": True,
            "view_analysis": True,
            "view_course_structure": True,
        },
        {
            "functionality": "actions",
            "action_list": True,
            "analysis": True,
            "ai_analysis": True,
        },
        {
            "functionality": "tracker_template",
            "create": True,
            "edit": True,
            "view": True,
            "preview": True,
            "delete": True,
        },
    ],
    "sales": [
        {
            "functionality": "ai",
            "ai_guruji": True,
            "ai_mira": True,
        },
        {
            "functionality": "contacts",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_contacts": True,
        },
        {
            "functionality": "companies",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_companies": True,
        },
        {
            "functionality": "deals",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_deals": True,
        },
        {
            "functionality": "gm_sheet",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_gm_sheet": True,
        },
        {
            "functionality": "sales_order",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_sales_order": True,
        },
        {
            "functionality": "handover",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "download": True,
            "my_handover": True,
        },
        {
            "functionality": "coach",
            "view": True,
            "share": True,
            "download": True,
        },
        {
            "functionality": "facilitator",
            "view": True,
            "share": True,
            "download": True,
            "edit": True,
            "create": True,
            "delete": True,
        },
        {
            "functionality": "pre_study",
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "view_deatils": True,
            "view_analysis": True,
            "view_course_structure": True,
        },
        {
            "edit": True,
            "view": True,
            "create": True,
            "delete": True,
            "functionality": "client_invoices",
        },
        {
            "functionality": "permissions",
            "view": True,
            "edit": True,
        },
        {
            "functionality": "finance_sheet",
            "view": True,
            "download": True,
        },
        {
            "functionality": "participants",
            "view": True,
            "download": True,
        },
    ],
}


DEFAULT_PERMISSIONS = [
    {
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "updates": True,
        "my_projects": True,
        "active_inactive": True,
        "close": True,
        "functionality": "project",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "download": True,
        "add_to_project": True,
        "mail": True,
        "share_profile": True,
        "functionality": "coach",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "accept": True,
        "reject": True,
        "functionality": "standard_field",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "download": True,
        "approve": True,
        "reject": True,
        "add_updates": True,
        "functionality": "registered_coach",
    },
    {
        "copy_link": True,
        "edit": True,
        "view": True,
        "send_mail": True,
        "functionality": "share_profile",
    },
    {
        "view": True,
        "functionality": "find_coach",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "download": True,
        
        "functionality": "facilitator",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "download": True,
        "approve": True,
        "reject": True,
        "add_updates": True,
        "functionality": "registered_facilitator",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "insights": True,
        "view_inside": True,
        "reject": True,
        "add_updates": True,
        "my_assessments": True,
        "functionality": "assessment",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "functionality": "questionnaire",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "functionality": "competency",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "functionality": "questions",
    },
    {
        "download": True,
        "view": True,
        "my_coaching_session_reports": True,
        "functionality": "coaching_session_reports",
    },
    {
        "download": True,
        "view": True,
        "my_live_session_reports": True,
        "functionality": "live_session_reports",
    },
    {
        "download": True,
        "view": True,
        "my_assessment_reports": True,
        "functionality": "assessments_reports",
    },
    {
        "download": True,
        "view": True,
        "my_course_reports": True,
        "functionality": "course_reports",
    },
    {
        "download": True,
        "view": True,
        "my_feedback_reports": True,
        "view_project_feedbacks": True,
        "functionality": "feedback_reports",
    },
    {
        "download": True,
        "view": True,
        "my_quiz_reports": True,
        "functionality": "quiz_reports",
    },
    {
        "download": True,
        "view": True,
        "functionality": "coach_ratings",
    },
    {
        "download": True,
        "view": True,
        "my_participant_reports": True,
        "functionality": "participant_reports",
    },
    {
        "generate": True,
        "download": True,
        "view": True,
        "my_closure_reports": True,
        "functionality": "closure_reports",
    },
    {
        "generate": True,
        "download": True,
        "view": True,
        "my_cancelled_session_reports": True,
        "functionality": "cancelled_session_reports",
    },
    {
        "upload": True,
        "edit": True,
        "view": True,
        "create": True,
        "view_engagements": True,
        "functionality": "coachee",
    },
    {
        "create": True,
        "edit": True,
        "delete": True,
        "view": True,
        "view_line_items": True,
        "download": True,
        "download_invoice": True,
        "preview_invoice": True,
        "updates": True,
        "my_purchase_orders": True,
        "functionality": "purchase_order",
    },
    {
        "functionality": "sales_order",
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "download": True,
        "my_sales_order": True,
    },
    {
        "functionality": "coach_finances",
        "view": True,
        "download": True,
    },
    {
        "functionality": "project_gm",
        "view": True,
        "download": True,
    },
    {
        "functionality": "facilitator_finances",
        "view": True,
        "po_analytics": True,
        "expenses": True,
        "download": True,
    },
    {
        "functionality": "project_finances",
        "view": True,
        "download": True,
    },
    {
        "functionality": "leaderboard",
        "view": True,
        "download": True,
    },
    {
        "functionality": "course_templates",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
    },
    {
        "functionality": "certificate",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
    },
    {
        "functionality": "video_library",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "play": True,
    },
    {
        "functionality": "pdf_library",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
    },
    {
        "functionality": "files_library",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "download": True,
    },
    {
        "functionality": "assignments",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
    },
    {
        "functionality": "resources",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "update_status": True,
        "assign_to_coachee": True,
        "create_tag": True,
        "approval": True,
        "preview": True,
    },
    {
        "functionality": "request_avalibility",
        "view": True,
        "download_avaliable_slots": True,
        "create": True,
        "edit": True,
        "delete": True,
    },
    {
        "functionality": "all_slots",
        "view": True,
        "edit": True,
    },
    {
        "functionality": "organization_and_hr",
        "view": True,
        "add_hr": True,
        "add_organization": True,
        "edit_hr": True,
        "edit_organization": True,
    },
    {
        "functionality": "email_templates",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "send_email": True,
        "preview": True,
    },
    {
        "functionality": "contract",
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
        "view": True,
        "master_coach_contract": True,
        "facilitator_contract": True,
        "download_coach_contract": True,
        "download_facilitator_contract": True,
    },
    {
        "functionality": "mira_ai",
        "mira_ai": True,
        "mira_ai_history": True,
        "chatbot_history": True,
    },
    {
        "functionality": "user_and_roles",
        "view": True,
    },
    {
        "functionality": "permissions",
        "view": True,
        "edit": True,
    },
    {
        "functionality": "meetings",
        "view": True,
    },
    {
        "functionality": "resources",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "update_status": True,
        "assign_to_coachee": True,
        "create_tag": True,
        "approval": True,
        "preview": True,
    },
    {
        "functionality": "mira_ai",
        "mira_ai": True,
        "mira_ai_history": True,
        "chatbot_history": True,
    },
    {
        "functionality": "form_templates",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
    },
    {
        "functionality": "form",
        "view": True,
        "create": True,
        "edit": True,
        "delete": True,
        "preview": True,
        "whatsapp_notification": True,
        "email_notification": True,
    },
    {
        "download": True,
        "view": True,
        "view_project_feedbacks": True,
        "functionality": "feedback",
    },
    {
        "functionality": "pre_study",
        "create": True,
        "delete": True,
        "edit": True,
        "view": True,
        "view_deatils": True,
        "view_analysis": True,
        "view_course_structure": True,
    },
    {
        "functionality": "actions",
        "action_list": True,
        "analysis": True,
        "ai_analysis": True,
    },
    {
        "functionality": "tracker_template",
        "create": True,
        "edit": True,
        "view": True,
        "preview": True,
        "delete": True,
    },
    {
        "functionality": "ai",
        "ai_guruji": True,
        "ai_mira": True,
    },
    {
        "functionality": "contacts",
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "download": True,
        "my_contacts": True,
    },
    {
        "functionality": "companies",
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "download": True,
        "my_companies": True,
    },
    {
        "functionality": "deals",
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "download": True,
        "my_deals": True,
    },
    {
        "edit": True,
        "view": True,
        "create": True,
        "delete": True,
        "functionality": "client_invoices",
    },
    {
        "functionality": "finance_sheet",
        "view": True,
        "download": True,
    },
    {
        "functionality": "participants",
        "view": True,
        "download": True,
    },
    {
        "functionality": "leads",
        "view": True,
        "download": True,
    },
    {
        "functionality": "performace_evaluation",
        "view": True,
        "download": True,
    },
    
]

wkhtmltopdf_path = os.environ.get("WKHTMLTOPDF_PATH", r"/usr/local/bin/wkhtmltopdf")

pdfkit_config = pdfkit.configuration(wkhtmltopdf=f"{wkhtmltopdf_path}")
logger = logging.getLogger(__name__)



FIELD_NAME_VALUES = {
    "location": "Work Location",
    "other_certification": "Assessment Certification",
    "area_of_expertise": "Industry",
    "job_roles": "Job roles",
    "companies_worked_in": "Companies worked in",
    "language": "Language Proficiency",
    "education": "Education institutions",
    "domain": "Functional Domain",
    "client_companies": "Client companies",
    "educational_qualification": "Educational Qualification",
    "city": "City",
    "country": "Country",
    "topic": "Topic",
    "project_type": "Project Type",
    "product_type": "Product Type",
    "category": "Category",
    "asset_location": "Location",
    "coaching_type": "Coaching Type",
    "client_experience_level": "Client Experience Level",
    "credentials_feels_like": "Credential Feels Like",
    "competency": "Competency",
    "function": "Function",
}



MODELS_TO_UPDATE = {
    "Coach": [
        "location",
        "other_certification",
        "area_of_expertise",
        "job_roles",
        "companies_worked_in",
        "language",
        "education",
        "domain",
        "client_companies",
        "educational_qualification",
        "client_experience_level",
    ],
    "Facilitator": [
        "location",
        "other_certification",
        "area_of_expertise",
        "job_roles",
        "companies_worked_in",
        "language",
        "education",
        "domain",
        "client_companies",
        "educational_qualification",
        "city",
        "country",
        "topic",
    ],
    "Learner": [
        "job_roles",
    ],
}
